### PR TITLE
Created a NetworkService object and NetworkService structs

### LINKED ISSUE #3: Add NetworkService skeleton
Add a `NetworkService` object in `enf/network.go`, modeled off of `FirewallService` in `enf/firewall.go`.

Add it to the Client object in `enf/enf.go` in the sameway that `AuthService` and `FirewallService` are.

This initial version will have no methods like `List*` or `Get*` yet.

### PR DESCRIPTION
**Pull request by dylanirlbeck**
Fixes #3 and #5

### CODE REVIEW

**Comment by drbild** [comment]
@dylanirlbeck Please edit the PR description (your first comment) to include "Fixes #3".  Then Github will close issue #3 when this PR is merged.

**Comment by dylanirlbeck** [comment]
@drbild This PR actually fixes two issues, so I think the new comment should reflect this.

**Comment by drbild** [comment]
@dylanirlbeck I don't see the code for #5 in this PR.  Did you forget to push the latest version?

**Comment by dylanirlbeck** [comment]
@drbild Oops I did forget. Just added a new commit for #5.

**Comment by dylanirlbeck** [comment]
Fixed.

**Pull request merged**
